name: VillagerLinkHighlighter
main: uk.tojoco.villagerlink.VillagerLinkHighlighterPlugin
version: 1.1.1
api-version: '1.21'
author: Tom Corby
description: Highlights villager bed/workstation link events with extended particles and sounds, now with added debug stick to force connections.
commands:
  villagerlink:
    description: VillagerLinkHighlighter admin commands
    usage: /villagerlink reload|stick
    permission: villagerlink.admin
permissions:
  villagerlink.admin:
    description: Allows reloading the plugin and getting the debug stick
    default: op